export { UploadImgChild } from './modal/upload-img'
export { AuthForm } from './auth-form'
export { RegistrationForm } from './registration-form'
export { PlayListModal } from './modal/playlist-modal'
export { ImgModal } from './modal/img-modal'